-- ═══════════════════════════════════════════════════════════════════
-- ICMRA Analytics — Database & Schema Setup
-- Run as ACCOUNTADMIN or SECURITYADMIN
-- ═══════════════════════════════════════════════════════════════════

-- ── Database ───────────────────────────────────────────────────────

CREATE DATABASE IF NOT EXISTS ICMRA_DB
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'ICMRA Fundraising Analytics Data Warehouse';

USE DATABASE ICMRA_DB;

-- ── Schemas ────────────────────────────────────────────────────────

CREATE SCHEMA IF NOT EXISTS RAW
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Raw source data landing zone — exact copy of source files';

CREATE SCHEMA IF NOT EXISTS STAGING
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Cleaned, typed, and renamed staging tables managed by dbt';

CREATE SCHEMA IF NOT EXISTS ANALYTICS
    DATA_RETENTION_TIME_IN_DAYS = 30
    COMMENT = 'Star schema marts — consumed by Power BI and reporting tools';

CREATE SCHEMA IF NOT EXISTS REPORTING
    DATA_RETENTION_TIME_IN_DAYS = 90
    COMMENT = 'Pre-aggregated executive reporting tables';

-- ── Role-Based Access Control (RBAC) ──────────────────────────────

-- Create roles
CREATE ROLE IF NOT EXISTS ICMRA_ETL_ROLE      COMMENT = 'dbt service account — read/write on all schemas';
CREATE ROLE IF NOT EXISTS ICMRA_ANALYST_ROLE  COMMENT = 'Data analysts — read-only on ANALYTICS';
CREATE ROLE IF NOT EXISTS ICMRA_BI_ROLE       COMMENT = 'Power BI service account — read-only on ANALYTICS + REPORTING';

-- Grant database usage
GRANT USAGE ON DATABASE ICMRA_DB TO ROLE ICMRA_ETL_ROLE;
GRANT USAGE ON DATABASE ICMRA_DB TO ROLE ICMRA_ANALYST_ROLE;
GRANT USAGE ON DATABASE ICMRA_DB TO ROLE ICMRA_BI_ROLE;

-- ETL role: full access to RAW, STAGING, ANALYTICS, REPORTING
GRANT USAGE ON SCHEMA ICMRA_DB.RAW TO ROLE ICMRA_ETL_ROLE;
GRANT USAGE ON SCHEMA ICMRA_DB.STAGING TO ROLE ICMRA_ETL_ROLE;
GRANT USAGE ON SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_ETL_ROLE;
GRANT USAGE ON SCHEMA ICMRA_DB.REPORTING TO ROLE ICMRA_ETL_ROLE;

GRANT CREATE TABLE ON SCHEMA ICMRA_DB.RAW TO ROLE ICMRA_ETL_ROLE;
GRANT CREATE TABLE ON SCHEMA ICMRA_DB.STAGING TO ROLE ICMRA_ETL_ROLE;
GRANT CREATE TABLE ON SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_ETL_ROLE;
GRANT CREATE TABLE ON SCHEMA ICMRA_DB.REPORTING TO ROLE ICMRA_ETL_ROLE;

GRANT CREATE VIEW ON SCHEMA ICMRA_DB.STAGING TO ROLE ICMRA_ETL_ROLE;
GRANT CREATE VIEW ON SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_ETL_ROLE;
GRANT CREATE VIEW ON SCHEMA ICMRA_DB.REPORTING TO ROLE ICMRA_ETL_ROLE;

-- Analyst role: read-only on ANALYTICS
GRANT USAGE ON SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_ANALYST_ROLE;

-- BI role: read-only on ANALYTICS + REPORTING
GRANT USAGE ON SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_BI_ROLE;
GRANT USAGE ON SCHEMA ICMRA_DB.REPORTING TO ROLE ICMRA_BI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_BI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ICMRA_DB.REPORTING TO ROLE ICMRA_BI_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ICMRA_DB.ANALYTICS TO ROLE ICMRA_BI_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ICMRA_DB.REPORTING TO ROLE ICMRA_BI_ROLE;

-- ── Role Hierarchy ─────────────────────────────────────────────────

GRANT ROLE ICMRA_ETL_ROLE     TO ROLE SYSADMIN;
GRANT ROLE ICMRA_ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE ICMRA_BI_ROLE      TO ROLE SYSADMIN;

-- Assign roles to users (replace with actual usernames)
-- GRANT ROLE ICMRA_ETL_ROLE     TO USER dbt_service_user;
-- GRANT ROLE ICMRA_ANALYST_ROLE TO USER data_analyst;
-- GRANT ROLE ICMRA_BI_ROLE      TO USER powerbi_service_user;
