table EducationLevel
	lineageTag: c0eb0a7e-1303-4f08-b940-ffbc6d6a13e2

	column EducationLevelID
		dataType: int64
		formatString: 0
		lineageTag: 1ebe509b-ea58-428f-af93-183397d6d737
		summarizeBy: none
		sourceColumn: EducationLevelID

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: e0d013ca-c17d-42aa-8100-d11be27757d4
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	partition EducationLevel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Admin\PowerBI\week 3\Project 1 Data\EducationLevel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EducationLevelID", Int64.Type}, {"EducationLevel", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

