table RatingLevel
	lineageTag: 168ad585-5edc-4c6e-b0ab-85192195da78

	column RatingID
		dataType: int64
		formatString: 0
		lineageTag: 699c239f-1842-4a5a-be89-35c85363fb6a
		summarizeBy: none
		sourceColumn: RatingID

		annotation SummarizationSetBy = Automatic

	column RatingLevel
		dataType: string
		lineageTag: 4867820b-8907-4835-b9cb-c3dd43aabb55
		summarizeBy: none
		sourceColumn: RatingLevel

		annotation SummarizationSetBy = Automatic

	partition RatingLevel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Admin\PowerBI\week 3\Project 1 Data\RatingLevel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RatingID", Int64.Type}, {"RatingLevel", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

