table SatisfiedLevel
	lineageTag: 2176ff11-bc69-4543-ac20-7c94880224bd

	column SatisfactionID
		dataType: int64
		formatString: 0
		lineageTag: ee08bd0e-f0dd-4fba-838a-a8887d613b8b
		summarizeBy: none
		sourceColumn: SatisfactionID

		annotation SummarizationSetBy = Automatic

	column SatisfactionLevel
		dataType: string
		lineageTag: 95236984-73a3-4b35-b9e6-1831d62cd5a0
		summarizeBy: none
		sourceColumn: SatisfactionLevel

		annotation SummarizationSetBy = Automatic

	partition SatisfiedLevel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Admin\PowerBI\week 3\Project 1 Data\SatisfiedLevel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SatisfactionID", Int64.Type}, {"SatisfactionLevel", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

